language: node_js

env:
  - NODE_ENV=development
  - DB_PWD=rootpassword

node_js:
  - "8"
  - "10"

services:
  - docker

before_install:
  - ./run-infra.sh

cache:
  directories:
    - "node_modules"

script:
  - npm run test
  - npm run build

after_script:
  - ./clean-infra.sh